from .pessoa import Pessoa
from .models import Coordenador
from .models import Aluno
from .models import Professor
from .models import AdministracaoDisciplina
from .models import AceiteMinistrarDisciplina
from .models import Disciplina
from .models import DisciplinaOfertada
from .models import AprovacaoSolicitacaoMatricula
from .models import LiberacaoMatricula
from .models import SolicitacaoMatricula
from .models import Atividade
from .models import VinculoAtividadeDisciplinaOfertada
from .models import Avaliacao
from .models import EntregaAtividade
from .models import Mensagem
